// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDb14kK_HxmF7TtrxN4iZT_7tQpWH4ifA',
    appId: '1:153351338665:web:4d0325a7348f93155847b8',
    messagingSenderId: '153351338665',
    projectId: 'market-navigator-project-6cb06',
    authDomain: 'market-navigator-project-6cb06.firebaseapp.com',
    storageBucket: 'market-navigator-project-6cb06.firebasestorage.app',
    measurementId: 'G-7W00QDJ89T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgu4myAf6O9A64mVx2hv-WLb7huaiEx84',
    appId: '1:153351338665:android:07c87ef66294cef65847b8',
    messagingSenderId: '153351338665',
    projectId: 'market-navigator-project-6cb06',
    storageBucket: 'market-navigator-project-6cb06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVXzf8mhvj--A_Mxfx_FEIEuHLASy3J40',
    appId: '1:153351338665:ios:5080ec10bd6e85005847b8',
    messagingSenderId: '153351338665',
    projectId: 'market-navigator-project-6cb06',
    storageBucket: 'market-navigator-project-6cb06.firebasestorage.app',
    iosBundleId: 'com.example.marketNavigator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVXzf8mhvj--A_Mxfx_FEIEuHLASy3J40',
    appId: '1:153351338665:ios:5080ec10bd6e85005847b8',
    messagingSenderId: '153351338665',
    projectId: 'market-navigator-project-6cb06',
    storageBucket: 'market-navigator-project-6cb06.firebasestorage.app',
    iosBundleId: 'com.example.marketNavigator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDb14kK_HxmF7TtrxN4iZT_7tQpWH4ifA',
    appId: '1:153351338665:web:4f35d8d0a87568125847b8',
    messagingSenderId: '153351338665',
    projectId: 'market-navigator-project-6cb06',
    authDomain: 'market-navigator-project-6cb06.firebaseapp.com',
    storageBucket: 'market-navigator-project-6cb06.firebasestorage.app',
    measurementId: 'G-86XDQN425P',
  );

}